/**
 * Init Container: Config Generator
 *
 * Pattern: This init container writes configuration to a shared volume
 * before the main application starts. This decouples configuration
 * generation (which may need secrets, environment introspection, or
 * template rendering) from the main application image.
 *
 * Use cases:
 *  - Render config templates with environment-specific values
 *  - Fetch secrets from a vault and write them to files
 *  - Generate TLS certificates or keys
 *  - Build environment-specific feature flag configs
 */

const fs = require('fs');
const path = require('path');

const CONFIG_DIR = process.env.CONFIG_DIR || '/etc/app-config';
const APP_ENV = process.env.APP_ENV || 'development';
const APP_VERSION = process.env.APP_VERSION || '1.0.0';
const FEATURE_FLAGS = process.env.FEATURE_FLAGS || 'notes-delete,notes-tags';

function generateAppConfig() {
  return {
    appName: 'Notes App',
    version: APP_VERSION,
    environment: APP_ENV,
    generatedAt: new Date().toISOString(),
    generatedBy: 'init-config-generator',
    database: {
      host: process.env.DB_HOST || 'postgres',
      port: parseInt(process.env.DB_PORT || '5432'),
      name: process.env.DB_NAME || 'notesdb',
    },
    features: FEATURE_FLAGS.split(',').reduce((acc, flag) => {
      acc[flag.trim()] = true;
      return acc;
    }, {}),
    logging: {
      level: APP_ENV === 'production' ? 'warn' : 'debug',
      format: APP_ENV === 'production' ? 'json' : 'pretty',
    },
    limits: {
      maxNotesPerRequest: APP_ENV === 'production' ? 100 : 1000,
      maxContentLength: 10000,
    },
  };
}

function generateNginxUpstream() {
  // Example: generate an nginx upstream config for the proxy sidecar
  return `# Auto-generated by init-config-generator
upstream main_app {
    server 127.0.0.1:3000;
    keepalive 32;
}
`;
}

function main() {
  console.log('[init-config-generator] Starting — init container for config generation');
  console.log(`[init-config-generator] Target config directory: ${CONFIG_DIR}`);

  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
    console.log(`[init-config-generator] Created config directory: ${CONFIG_DIR}`);
  }

  const appConfig = generateAppConfig();
  const appConfigPath = path.join(CONFIG_DIR, 'app-config.json');
  fs.writeFileSync(appConfigPath, JSON.stringify(appConfig, null, 2));
  console.log(`[init-config-generator] Written: ${appConfigPath}`);
  console.log('[init-config-generator] Config contents:', JSON.stringify(appConfig, null, 2));

  const nginxConfig = generateNginxUpstream();
  const nginxConfigPath = path.join(CONFIG_DIR, 'upstream.conf');
  fs.writeFileSync(nginxConfigPath, nginxConfig);
  console.log(`[init-config-generator] Written: ${nginxConfigPath}`);

  // Write a readiness marker so the main app can verify init ran
  const markerPath = path.join(CONFIG_DIR, '.init-complete');
  fs.writeFileSync(markerPath, new Date().toISOString());
  console.log(`[init-config-generator] Written init marker: ${markerPath}`);

  console.log('[init-config-generator] Done — exiting with code 0');
  process.exit(0);
}

main();
